# -----------------------------------------------
# Vulture
# Version: ${project.version}
#
# Created by: Foulest (https://github.com/Foulest/Vulture)
# License: GPLv3 (https://github.com/Foulest/Vulture/LICENSE)
# -----------------------------------------------
vulture:
  # -----------------------------------------------
  # General Settings
  # -----------------------------------------------
  general:
    prefix: '&e[Vulture]'
    banMessage:
      - '&c%player% has been removed from the network.'
    resetViolations: 600
  # -----------------------------------------------
  # Blocked Settings
  #
  # Payloads, mods, and commands can be blocked below.
  # The commands section supports RegEx.
  #
  # Players that send blocked payloads will be kicked.
  # Players that send blocked commands will have their command blocked.
  #
  # For information about what payloads and mods are, visit the links below:
  # https://github.com/Foulest/Vulture/blob/main/src/main/java/net/foulest/vulture/check/type/clientbrand/type/PayloadType.java
  # https://github.com/Foulest/Vulture/blob/main/src/main/java/net/foulest/vulture/check/type/clientbrand/type/ModType.java
  # https://github.com/Foulest/Vulture/blob/main/src/main/java/net/foulest/vulture/check/type/clientbrand/ClientBrand.java
  # -----------------------------------------------
  blocked:
    payloads:
      - GalactiCraft
      - Tinkers Construct
      - InventoryTweaks
      - Aqua Acrobatics
    mods:
      - aquaacrobatics
    commands:
      - /calc
      - /eval
      - /solve
      - /h.* readtext
      - /pe.*x promote
      - /pe.*x demote
      - /promote
      - /demote
      - /m.*v.* \^
      - /m.*v.*help <
      - /\$
  # -----------------------------------------------
  # Check Settings
  #
  # The 'enabled' option turns the check on/off.
  # The 'maxViolations' option sets the maximum number of violations a player can have before being banned.
  # The 'banCommand' option sets the command executed when a player is banned.
  # Placeholders: %player%, %check%
  #
  # Some checks have additional and/or missing options.
  # For example, some checks are missing the 'maxViolations' and 'banCommand' options.
  # These checks do not have a maximum amount of violations and do not ban players; they only kick players.
  # -----------------------------------------------
  checks:
    badpackets:
      A:
        enabled: true
      B:
        enabled: true
      C:
        enabled: true
      D:
        enabled: true
      E:
        enabled: true
      F:
        enabled: true
      G:
        enabled: true
    clientbrand:
      enabled: true
    inventory:
      A:
        enabled: true
      B:
        enabled: true
      C:
        enabled: true
      D:
        enabled: true
      E:
        enabled: true
      F:
        enabled: true
      G:
        enabled: true
      H:
        enabled: true
      I:
        enabled: true
      J:
        enabled: true
      K:
        enabled: true
    pingspoof:
      A:
        enabled: true
      B:
        enabled: true
        maxPing: 1000
        maxAveragePing: 500
        maxPingDeviation: 500
  # -----------------------------------------------
  # IP Whitelist Settings
  #
  # This ensures that specified players need to log in with the specified IP address.
  # This completely prevents players (staff) accounts from being hijacked.
  # -----------------------------------------------
  ip-whitelist:
    enabled: false
    whitelist: [ ]
  # -----------------------------------------------
  # Protection Settings
  #
  # Note: Modifying these settings is NOT recommended and only for experienced server owners.
  # Disabling protections will allow players to use exploits and send invalid or modified packets.
  # Leave it at the default value if unsure what a specific protection does.
  # -----------------------------------------------
  protections:
    exploits:
      world:
        invalid-block-break: true
        invalid-block-place: true
        block-nether-ceiling: true
        block-commands-while-sleeping: true
        fix-pearl-phasing: true
      pistons:
        block-moving-entities: true
      portals:
        block-affected-mobs: true
    packets:
      max-packets-per-tick: 400
      max-packets-per-second: 600
      max-packets-smoothed: 500
      max-time-over-server: 100
      abilities:
        duplicate-flying: true
        invalid-flight-allowed: true
        invalid-flying: true
        invalid-creative-mode: true
        invalid-god-mode: true
      beacon:
        invalid-conditions: true
        invalid-data: true
        invalid-effect: true
        invalid-tier: true
      block-placement:
        invalid-block-position: true
        invalid-distance: true
        invalid-up-cursor-bounds: true
        invalid-up-cursor-position: true
        invalid-up-pitch: true
        invalid-down-cursor-bounds: true
        invalid-down-cursor-position: true
        invalid-down-pitch: true
        invalid-east-cursor-bounds: true
        invalid-east-cursor-position: true
        invalid-east-yaw: true
        invalid-west-cursor-bounds: true
        invalid-west-cursor-position: true
        invalid-west-yaw: true
        invalid-north-cursor-bounds: true
        invalid-north-cursor-position: true
        invalid-north-yaw: true
        invalid-south-cursor-bounds: true
        invalid-south-cursor-position: true
        invalid-south-yaw: true
        invalid-other-cursor-position: true
        invalid-other-block-position: true
      book-edit:
        invalid-conditions: true
        invalid-data: true
      book-open:
        invalid-conditions: true
      book-sign:
        invalid-conditions: true
        invalid-data: true
      chat-message:
        invalid-conditions: true
        invalid-message: true
      close-window:
        invalid-conditions: true
      command-block:
        invalid-conditions: true
      creative-inventory-action:
        invalid-conditions: true
        invalid-slot: true
      digging:
        invalid-block-type: true
        invalid-block-position: true
        invalid-distance: true
      entity-action:
        invalid-entity-id: true
        invalid-action: true
      flying:
        invalid-pitch: true
        invalid-position-data: true
        invalid-rotation-data: true
        invalid-y-data: true
      held-item-change:
        invalid-conditions: true
        invalid-slot: true
        invalid-slot-change: true
      drop-item:
        invalid-data: true
      interact-entity:
        invalid-conditions: true
        invalid-distance: true
      item-name:
        invalid-data: true
        invalid-size: true
      open-horse-inventory:
        invalid-conditions: true
        invalid-vehicle: true
        invalid-tamed: true
      plugin-message:
        invalid-channel-name: true
        invalid-size: true
      release-use-item:
        invalid-data: true
      respawn:
        invalid-conditions: true
      riding-jump:
        invalid-conditions: true
        invalid-jump-boost: true
      settings:
        invalid-locale: true
        invalid-view-distance: true
      spectate:
        invalid-conditions: true
        invalid-target: true
      start-sneaking:
        invalid-conditions: true
      steer-vehicle:
        invalid-conditions: true
        invalid-dismount-value: true
        invalid-non-dismount-value: true
        invalid-jump: true
        invalid-value: true
      stop-sleeping:
        invalid-conditions: true
      tab-complete:
        invalid-message: true
      trade-select:
        invalid-data: true
      update-sign:
        invalid-data: true
      window-click:
        invalid-clone-button: true
        invalid-pickup-all-button: true
        invalid-pickup-button: true
        invalid-quick-craft-button: true
        invalid-quick-move-button: true
        invalid-swap-button: true
        invalid-throw-button: true
        invalid-slot: true
        invalid-type: true
      window-confirmation:
        invalid-window-id: true
        not-accepted: true
